//
// Generated By: dol2asm
// Translation Unit: c_API
//

#include "SSystem/SComponent/c_API.h"
#include "dolphin/types.h"

//
// External References:
//

extern u8 g_mDoGph_graphicInfo;
void mDoGph_Create();
void mDoGph_BeforeOfDraw();
void mDoGph_AfterOfDraw();
void mDoGph_Painter();
void mDoGph_BlankingON();
void mDoGph_BlankingOFF();

//
// Declarations:
//

/* ############################################################################################## */
/* 803950D8-803950F8 0020+00 s=0 e=3 z=0  None .data      g_cAPI_Interface */
cAPI_Interface g_cAPI_Interface = {
    &g_mDoGph_graphicInfo, mDoGph_Create,     mDoGph_BeforeOfDraw, mDoGph_AfterOfDraw,
    mDoGph_Painter,        mDoGph_BlankingON, mDoGph_BlankingOFF,  NULL,
};
