//
// Generated by dtk
// Translation Unit: c_bg_s_lin_chk.cpp
//

#include "SSystem/SComponent/c_bg_s_lin_chk.h"
#include "dolphin/types.h"

/* 80247418-80247480       .text ct__11cBgS_LinChkFv */
void cBgS_LinChk::ct() {
    /* Nonmatching */
}

/* 80247480-80247500       .text Set2__11cBgS_LinChkFP4cXyzP4cXyzUi */
void cBgS_LinChk::Set2(cXyz*, cXyz*, unsigned int) {
    /* Nonmatching */
}
