//
// Generated by dtk
// Translation Unit: c_bg_s_chk.cpp
//

#include "SSystem/SComponent/c_bg_s_chk.h"
#include "dolphin/types.h"

/* 80247304-8024734C       .text __dt__8cBgS_ChkFv */
cBgS_Chk::~cBgS_Chk() {
    /* Nonmatching */
}

/* 8024734C-8024738C       .text ChkSameActorPid__8cBgS_ChkCFUi */
void cBgS_Chk::ChkSameActorPid(unsigned int) const {
    /* Nonmatching */
}
