//
// Generated by dtk
// Translation Unit: c_m2d.cpp
//

#include "SSystem/SComponent/c_m2d.h"
#include "dolphin/types.h"

/* 80249DAC-8024A0E0       .text cM2d_CrossCirLin__FR8cM2dGCirffffPfPf */
void cM2d_CrossCirLin(cM2dGCir&, float, float, float, float, float*, float*) {
    /* Nonmatching */
}
