//
// Generated by dtk
// Translation Unit: c_m2d_g_box.cpp
//

#include "SSystem/SComponent/c_m2d_g_box.h"
#include "dolphin/types.h"

/* 8024A0E0-8024A104       .text Set__8cM2dGBoxFR3cXyR3cXy */
void cM2dGBox::Set(cXy&, cXy&) {
    /* Nonmatching */
}

/* 8024A104-8024A400       .text GetLen__8cM2dGBoxCFRC3cXy */
void cM2dGBox::GetLen(const cXy&) const {
    /* Nonmatching */
}
