//
// Generated by dtk
// Translation Unit: c_m3d_g_sph.cpp
//

#include "SSystem/SComponent/c_m3d_g_sph.h"
#include "dolphin/types.h"

/* 8025238C-80252624       .text SetC__8cM3dGSphFRC4cXyz */
void cM3dGSph::SetC(const cXyz&) {
    /* Nonmatching */
}

/* 80252624-80252750       .text SetR__8cM3dGSphFf */
void cM3dGSph::SetR(float) {
    /* Nonmatching */
}

/* 80252750-8025277C       .text cross__8cM3dGSphCFPC8cM3dGSphP4cXyz */
void cM3dGSph::cross(const cM3dGSph*, cXyz*) const {
    /* Nonmatching */
}

/* 8025277C-802527AC       .text cross__8cM3dGSphCFPC8cM3dGCylP4cXyz */
void cM3dGSph::cross(const cM3dGCyl*, cXyz*) const {
    /* Nonmatching */
}

/* 802527AC-802527D4       .text cross__8cM3dGSphCFPC8cM3dGSphPf */
void cM3dGSph::cross(const cM3dGSph*, float*) const {
    /* Nonmatching */
}
