//
// Generated by dtk
// Translation Unit: c_m3d_g_tri.cpp
//

#include "SSystem/SComponent/c_m3d_g_tri.h"
#include "dolphin/types.h"

/* 802527D4-80252878       .text __ct__8cM3dGTriFPC3VecPC3VecPC3Vec */
cM3dGTri::cM3dGTri(const Vec*, const Vec*, const Vec*) {
    /* Nonmatching */
}

/* 80252878-802528A4       .text cross__8cM3dGTriCFPC8cM3dGCylP3Vec */
void cM3dGTri::cross(const cM3dGCyl*, Vec*) const {
    /* Nonmatching */
}
