//
// Generated by dtk
// Translation Unit: c_m3d_g_cyl.cpp
//

#include "SSystem/SComponent/c_m3d_g_cyl.h"
#include "dolphin/types.h"

/* 80251D88-80252020       .text SetC__8cM3dGCylFRC4cXyz */
void cM3dGCyl::SetC(const cXyz&) {
    /* Nonmatching */
}

/* 80252020-8025214C       .text SetH__8cM3dGCylFf */
void cM3dGCyl::SetH(float) {
    /* Nonmatching */
}

/* 8025214C-80252278       .text SetR__8cM3dGCylFf */
void cM3dGCyl::SetR(float) {
    /* Nonmatching */
}

/* 80252278-8025229C       .text cross__8cM3dGCylCFPC8cM3dGSphP4cXyz */
void cM3dGCyl::cross(const cM3dGSph*, cXyz*) const {
    /* Nonmatching */
}

/* 8025229C-802522BC       .text cross__8cM3dGCylCFPC8cM3dGCylPf */
void cM3dGCyl::cross(const cM3dGCyl*, float*) const {
    /* Nonmatching */
}

/* 802522BC-802522DC       .text cross__8cM3dGCylCFPC8cM3dGCylP4cXyz */
void cM3dGCyl::cross(const cM3dGCyl*, cXyz*) const {
    /* Nonmatching */
}

/* 802522DC-80252304       .text cross__8cM3dGCylCFPC8cM3dGSphPf */
void cM3dGCyl::cross(const cM3dGSph*, float*) const {
    /* Nonmatching */
}
