//
// Generated by dtk
// Translation Unit: m_Do_controller_pad.cpp
//

#include "m_Do/m_Do_controller_pad.h"
#include "dolphin/types.h"

/* 80007598-800078C0       .text mDoCPd_Convert__FP27interface_of_controller_padP10JUTGamePad */
void mDoCPd_Convert(interface_of_controller_pad*, JUTGamePad*) {
    /* Nonmatching */
}

/* 800078C0-80007A70       .text mDoCPd_Read__Fv */
void mDoCPd_Read() {
    /* Nonmatching */
}

/* 80007A70-80007BBC       .text mDoCPd_Create__Fv */
void mDoCPd_Create() {
    /* Nonmatching */
}
