//
// Generated by dtk
// Translation Unit: JUTNameTab.cpp
//

#include "JSystem/JUtility/JUTNameTab.h"
#include "dolphin/types.h"

/* 802C199C-802C19DC       .text __ct__10JUTNameTabFv */
JUTNameTab::JUTNameTab() {
    /* Nonmatching */
}

/* 802C19DC-802C1A18       .text __ct__10JUTNameTabFPC7ResNTAB */
JUTNameTab::JUTNameTab(const ResNTAB*) {
    /* Nonmatching */
}

/* 802C1A18-802C1A54       .text setResource__10JUTNameTabFPC7ResNTAB */
void JUTNameTab::setResource(const ResNTAB*) {
    /* Nonmatching */
}

/* 802C1A54-802C1B38       .text getIndex__10JUTNameTabCFPCc */
void JUTNameTab::getIndex(const char*) const {
    /* Nonmatching */
}

/* 802C1B38-802C1BD4       .text getName__10JUTNameTabCFUs */
void JUTNameTab::getName(unsigned short) const {
    /* Nonmatching */
}

/* 802C1BD4-802C1C04       .text calcKeyCode__10JUTNameTabCFPCc */
void JUTNameTab::calcKeyCode(const char*) const {
    /* Nonmatching */
}
