//
// Generated by dtk
// Translation Unit: JUTPalette.cpp
//

#include "JSystem/JUtility/JUTPalette.h"
#include "dolphin/types.h"

/* 802C188C-802C1918       .text storeTLUT__10JUTPaletteF7_GXTlutP7ResTLUT */
void JUTPalette::storeTLUT(_GXTlut, ResTLUT*) {
    /* Nonmatching */
}

/* 802C1918-802C1958       .text storeTLUT__10JUTPaletteF7_GXTlut10_GXTlutFmt15JUTTransparencyUsPv */
void JUTPalette::storeTLUT(_GXTlut, _GXTlutFmt, JUTTransparency, unsigned short, void*) {
    /* Nonmatching */
}

/* 802C1958-802C199C       .text load__10JUTPaletteFv */
void JUTPalette::load() {
    /* Nonmatching */
}
