//
// Generated by dtk
// Translation Unit: f_pc_node.cpp
//

#include "f_pc/f_pc_node.h"
#include "dolphin/types.h"

/* 8003EFC8-8003EFEC       .text fpcNd_DrawMethod__FP21nodedraw_method_classPv */
void fpcNd_DrawMethod(nodedraw_method_class*, void*) {
    /* Nonmatching */
}

/* 8003EFEC-8003F058       .text fpcNd_Draw__FP18process_node_class */
void fpcNd_Draw(process_node_class*) {
    /* Nonmatching */
}

/* 8003F058-8003F0B4       .text fpcNd_Execute__FP18process_node_class */
void fpcNd_Execute(process_node_class*) {
    /* Nonmatching */
}

/* 8003F0B4-8003F134       .text fpcNd_IsCreatingFromUnder__FPv */
void fpcNd_IsCreatingFromUnder(void*) {
    /* Nonmatching */
}

/* 8003F134-8003F174       .text fpcNd_IsDeleteTiming__FP18process_node_class */
void fpcNd_IsDeleteTiming(process_node_class*) {
    /* Nonmatching */
}

/* 8003F174-8003F19C       .text fpcNd_IsDelete__FP18process_node_class */
void fpcNd_IsDelete(process_node_class*) {
    /* Nonmatching */
}

/* 8003F19C-8003F200       .text fpcNd_Delete__FP18process_node_class */
void fpcNd_Delete(process_node_class*) {
    /* Nonmatching */
}

/* 8003F200-8003F29C       .text fpcNd_Create__FP18process_node_class */
void fpcNd_Create(process_node_class*) {
    /* Nonmatching */
}
