//
// Generated by dtk
// Translation Unit: f_pc_delete_tag.cpp
//

#include "f_pc/f_pc_delete_tag.h"
#include "dolphin/types.h"

/* 8003D170-8003D188       .text fpcDtTg_IsEmpty__Fv */
void fpcDtTg_IsEmpty() {
    /* Nonmatching */
}

/* 8003D188-8003D1BC       .text fpcDtTg_ToDeleteQ__FP16delete_tag_class */
void fpcDtTg_ToDeleteQ(delete_tag_class*) {
    /* Nonmatching */
}

/* 8003D1BC-8003D1DC       .text fpcDtTg_DeleteQTo__FP16delete_tag_class */
void fpcDtTg_DeleteQTo(delete_tag_class*) {
    /* Nonmatching */
}

/* 8003D1DC-8003D25C       .text fpcDtTg_Do__FP16delete_tag_classPFPv_i */
void fpcDtTg_Do(delete_tag_class*, int (*)(void*)) {
    /* Nonmatching */
}

/* 8003D25C-8003D280       .text fpcDtTg_Init__FP16delete_tag_classPv */
void fpcDtTg_Init(delete_tag_class*, void*) {
    /* Nonmatching */
}
