//
// Generated by dtk
// Translation Unit: f_pc_create_req.cpp
//

#include "f_pc/f_pc_create_req.h"
#include "dolphin/types.h"

/* 8003CD0C-8003CD28       .text fpcCtRq_isCreatingByID__FP10create_tagPUi */
void fpcCtRq_isCreatingByID(create_tag*, unsigned int*) {
    /* Nonmatching */
}

/* 8003CD28-8003CD60       .text fpcCtRq_IsCreatingByID__FUi */
void fpcCtRq_IsCreatingByID(unsigned int) {
    /* Nonmatching */
}

/* 8003CD60-8003CD9C       .text fpcCtRq_CreateQTo__FP14create_request */
void fpcCtRq_CreateQTo(create_request*) {
    /* Nonmatching */
}

/* 8003CD9C-8003CDE0       .text fpcCtRq_ToCreateQ__FP14create_request */
void fpcCtRq_ToCreateQ(create_request*) {
    /* Nonmatching */
}

/* 8003CDE0-8003CE54       .text fpcCtRq_Delete__FP14create_request */
void fpcCtRq_Delete(create_request*) {
    /* Nonmatching */
}

/* 8003CE54-8003CEEC       .text fpcCtRq_Cancel__FP14create_request */
void fpcCtRq_Cancel(create_request*) {
    /* Nonmatching */
}

/* 8003CEEC-8003CF08       .text fpcCtRq_IsDoing__FP14create_request */
void fpcCtRq_IsDoing(create_request*) {
    /* Nonmatching */
}

/* 8003CF08-8003CFC4       .text fpcCtRq_Do__FP14create_request */
void fpcCtRq_Do(create_request*) {
    /* Nonmatching */
}

/* 8003CFC4-8003CFF0       .text fpcCtRq_Handler__Fv */
void fpcCtRq_Handler() {
    /* Nonmatching */
}

/* 8003CFF0-8003D078       .text fpcCtRq_Create__FP11layer_classUlP27create_request_method_class */
void fpcCtRq_Create(layer_class*, unsigned long, create_request_method_class*) {
    /* Nonmatching */
}
