//
// Generated by dtk
// Translation Unit: f_pc_draw_priority.cpp
//

#include "f_pc/f_pc_draw_priority.h"
#include "dolphin/types.h"

/* 8003D580-8003D588       .text fpcDwPi_Get__FP19draw_priority_class */
void fpcDwPi_Get(draw_priority_class*) {
    /* Nonmatching */
}

/* 8003D588-8003D590       .text fpcDwPi_Set__FP19draw_priority_classs */
void fpcDwPi_Set(draw_priority_class*, short) {
    /* Nonmatching */
}

/* 8003D590-8003D5B0       .text fpcDwPi_Init__FP19draw_priority_classs */
void fpcDwPi_Init(draw_priority_class*, short) {
    /* Nonmatching */
}
