//
// Generated by dtk
// Translation Unit: f_pc_draw.cpp
//

#include "f_pc/f_pc_draw.h"
#include "dolphin/types.h"

/* 8004042C-800404CC       .text fpcDw_Execute__FP18base_process_class */
void fpcDw_Execute(base_process_class*) {
    /* Nonmatching */
}

/* 800404CC-80040520       .text fpcDw_Handler__FPFPFPvPv_i_iPFPvPv_i */
void fpcDw_Handler(int (*)(int (*)(void*, void*)), int (*)(void*, void*)) {
    /* Nonmatching */
}
