//
// Generated by dtk
// Translation Unit: f_pc_line_tag.cpp
//

#include "f_pc/f_pc_line_tag.h"
#include "dolphin/types.h"

/* 80040080-800400D8       .text fpcLnTg_Move__FP8line_tagi */
void fpcLnTg_Move(line_tag*, int) {
    /* Nonmatching */
}

/* 800400D8-8004010C       .text fpcLnTg_QueueTo__FP8line_tag */
void fpcLnTg_QueueTo(line_tag*) {
    /* Nonmatching */
}

/* 8004010C-80040164       .text fpcLnTg_ToQueue__FP8line_tagi */
void fpcLnTg_ToQueue(line_tag*, int) {
    /* Nonmatching */
}

/* 80040164-80040198       .text fpcLnTg_Init__FP8line_tagPv */
void fpcLnTg_Init(line_tag*, void*) {
    /* Nonmatching */
}
