//
// Generated by dtk
// Translation Unit: f_pc_line_iter.cpp
//

#include "f_pc/f_pc_line_iter.h"
#include "dolphin/types.h"

/* 80040198-80040200       .text fpcLnIt_MethodCall__FP16create_tag_classP13method_filter */
void fpcLnIt_MethodCall(create_tag_class*, method_filter*) {
    /* Nonmatching */
}

/* 80040200-8004023C       .text fpcLnIt_Queue__FPFPvPv_i */
void fpcLnIt_Queue(int (*)(void*, void*)) {
    /* Nonmatching */
}
