//
// Generated by dtk
// Translation Unit: f_pc_layer_iter.cpp
//

#include "f_pc/f_pc_layer_iter.h"
#include "dolphin/types.h"

/* 8003DE00-8003DE38       .text fpcLyIt_OnlyHere__FP11layer_classPFPvPv_iPv */
void fpcLyIt_OnlyHere(layer_class*, int (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003DE38-8003DEA0       .text fpcLyIt_OnlyHereLY__FP11layer_classPFPvPv_iPv */
void fpcLyIt_OnlyHereLY(layer_class*, int (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003DEA0-8003DED8       .text fpcLyIt_Judge__FP11layer_classPFPvPv_PvPv */
void fpcLyIt_Judge(layer_class*, void* (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003DED8-8003DF4C       .text fpcLyIt_AllJudge__FPFPvPv_PvPv */
void fpcLyIt_AllJudge(void* (*)(void*, void*), void*) {
    /* Nonmatching */
}
