//
// Generated by dtk
// Translation Unit: f_pc_creator.cpp
//

#include "f_pc/f_pc_creator.h"
#include "dolphin/types.h"

/* 8003D0E8-8003D108       .text fpcCt_IsCreatingByID__FUi */
void fpcCt_IsCreatingByID(unsigned int) {
    /* Nonmatching */
}

/* 8003D108-8003D12C       .text fpcCt_IsDoing__FP18base_process_class */
void fpcCt_IsDoing(base_process_class*) {
    /* Nonmatching */
}

/* 8003D12C-8003D150       .text fpcCt_Abort__FP18base_process_class */
void fpcCt_Abort(base_process_class*) {
    /* Nonmatching */
}

/* 8003D150-8003D170       .text fpcCt_Handler__Fv */
void fpcCt_Handler() {
    /* Nonmatching */
}
