//
// Generated by dtk
// Translation Unit: f_pc_stdcreate_req.cpp
//

#include "f_pc/f_pc_stdcreate_req.h"
#include "dolphin/types.h"

/* 80040648-8004069C       .text fpcSCtRq_phase_Load__FP29standard_create_request_class */
void fpcSCtRq_phase_Load(standard_create_request_class*) {
    /* Nonmatching */
}

/* 8004069C-80040704       .text fpcSCtRq_phase_CreateProcess__FP29standard_create_request_class */
void fpcSCtRq_phase_CreateProcess(standard_create_request_class*) {
    /* Nonmatching */
}

/* 80040704-8004073C       .text fpcSCtRq_phase_SubCreateProcess__FP29standard_create_request_class */
void fpcSCtRq_phase_SubCreateProcess(standard_create_request_class*) {
    /* Nonmatching */
}

/* 8004073C-80040794       .text fpcSCtRq_phase_IsComplete__FP29standard_create_request_class */
void fpcSCtRq_phase_IsComplete(standard_create_request_class*) {
    /* Nonmatching */
}

/* 80040794-800407E4       .text fpcSCtRq_phase_PostMethod__FP29standard_create_request_class */
void fpcSCtRq_phase_PostMethod(standard_create_request_class*) {
    /* Nonmatching */
}

/* 800407E4-800407EC       .text fpcSCtRq_phase_Done__FP29standard_create_request_class */
void fpcSCtRq_phase_Done(standard_create_request_class*) {
    /* Nonmatching */
}

/* 800407EC-8004085C       .text fpcSCtRq_Handler__FP29standard_create_request_class */
void fpcSCtRq_Handler(standard_create_request_class*) {
    /* Nonmatching */
}

/* 8004085C-80040864       .text fpcSCtRq_Delete__FP29standard_create_request_class */
void fpcSCtRq_Delete(standard_create_request_class*) {
    /* Nonmatching */
}

/* 80040864-8004086C       .text fpcSCtRq_Cancel__FP29standard_create_request_class */
void fpcSCtRq_Cancel(standard_create_request_class*) {
    /* Nonmatching */
}

/* 8004086C-80040900       .text fpcSCtRq_Request__FP11layer_classsPFPvPv_iPvPv */
void fpcSCtRq_Request(layer_class*, short, int (*)(void*, void*), void*, void*) {
    /* Nonmatching */
}
