//
// Generated by dtk
// Translation Unit: f_pc_create_tag.cpp
//

#include "f_pc/f_pc_create_tag.h"
#include "dolphin/types.h"

/* 8003D078-8003D0A4       .text fpcCtTg_ToCreateQ__FP10create_tag */
void fpcCtTg_ToCreateQ(create_tag*) {
    /* Nonmatching */
}

/* 8003D0A4-8003D0C4       .text fpcCtTg_CreateQTo__FP10create_tag */
void fpcCtTg_CreateQTo(create_tag*) {
    /* Nonmatching */
}

/* 8003D0C4-8003D0E8       .text fpcCtTg_Init__FP10create_tagPv */
void fpcCtTg_Init(create_tag*, void*) {
    /* Nonmatching */
}
