//
// Generated by dtk
// Translation Unit: f_pc_leaf.cpp
//

#include "f_pc/f_pc_leaf.h"
#include "dolphin/types.h"

/* 8003DC78-8003DC9C       .text fpcLf_GetPriority__FP14leafdraw_class */
void fpcLf_GetPriority(leafdraw_class*) {
    /* Nonmatching */
}

/* 8003DC9C-8003DCC0       .text fpcLf_DrawMethod__FP21leafdraw_method_classPv */
void fpcLf_DrawMethod(leafdraw_method_class*, void*) {
    /* Nonmatching */
}

/* 8003DCC0-8003DCF8       .text fpcLf_Draw__FP14leafdraw_class */
void fpcLf_Draw(leafdraw_class*) {
    /* Nonmatching */
}

/* 8003DCF8-8003DD20       .text fpcLf_Execute__FP14leafdraw_class */
void fpcLf_Execute(leafdraw_class*) {
    /* Nonmatching */
}

/* 8003DD20-8003DD48       .text fpcLf_IsDelete__FP14leafdraw_class */
void fpcLf_IsDelete(leafdraw_class*) {
    /* Nonmatching */
}

/* 8003DD48-8003DD8C       .text fpcLf_Delete__FP14leafdraw_class */
void fpcLf_Delete(leafdraw_class*) {
    /* Nonmatching */
}

/* 8003DD8C-8003DE00       .text fpcLf_Create__FP14leafdraw_class */
void fpcLf_Create(leafdraw_class*) {
    /* Nonmatching */
}
