//
// Generated by dtk
// Translation Unit: f_pc_pause.cpp
//

#include "f_pc/f_pc_pause.h"
#include "dolphin/types.h"

/* 8004031C-80040340       .text fpcPause_IsEnable__FPvUc */
void fpcPause_IsEnable(void*, unsigned char) {
    /* Nonmatching */
}

/* 80040340-800403AC       .text fpcPause_Enable__FPvUc */
void fpcPause_Enable(void*, unsigned char) {
    /* Nonmatching */
}

/* 800403AC-80040420       .text fpcPause_Disable__FPvUc */
void fpcPause_Disable(void*, unsigned char) {
    /* Nonmatching */
}

/* 80040420-8004042C       .text fpcPause_Init__FPv */
void fpcPause_Init(void*) {
    /* Nonmatching */
}
