//
// Generated by dtk
// Translation Unit: f_pc_load.cpp
//

#include "f_pc/f_pc_load.h"
#include "dolphin/types.h"

/* 8003E230-8003E280       .text fpcLd_Use__Fs */
void fpcLd_Use(short) {
    /* Nonmatching */
}

/* 8003E280-8003E2A4       .text fpcLd_IsLoaded__Fs */
void fpcLd_IsLoaded(short) {
    /* Nonmatching */
}

/* 8003E2A4-8003E2C8       .text fpcLd_Free__Fs */
void fpcLd_Free(short) {
    /* Nonmatching */
}

/* 8003E2C8-8003E318       .text fpcLd_Load__Fs */
void fpcLd_Load(short) {
    /* Nonmatching */
}
