//
// Generated by dtk
// Translation Unit: f_pc_searcher.cpp
//

#include "f_pc/f_pc_searcher.h"
#include "dolphin/types.h"

/* 80040050-80040068       .text fpcSch_JudgeForPName__FPvPv */
void fpcSch_JudgeForPName(void*, void*) {
    /* Nonmatching */
}

/* 80040068-80040080       .text fpcSch_JudgeByID__FPvPv */
void fpcSch_JudgeByID(void*, void*) {
    /* Nonmatching */
}
