//
// Generated by dtk
// Translation Unit: f_pc_priority.cpp
//

#include "f_pc/f_pc_priority.h"
#include "dolphin/types.h"

/* 8003FC08-8003FC28       .text fpcPi_IsInQueue__FP22process_priority_class */
void fpcPi_IsInQueue(process_priority_class*) {
    /* Nonmatching */
}

/* 8003FC28-8003FC60       .text fpcPi_QueueTo__FP22process_priority_class */
void fpcPi_QueueTo(process_priority_class*) {
    /* Nonmatching */
}

/* 8003FC60-8003FCEC       .text fpcPi_ToQueue__FP22process_priority_class */
void fpcPi_ToQueue(process_priority_class*) {
    /* Nonmatching */
}

/* 8003FCEC-8003FD40       .text fpcPi_GetFromQueue__Fv */
void fpcPi_GetFromQueue() {
    /* Nonmatching */
}

/* 8003FD40-8003FD8C       .text fpcPi_Delete__FP22process_priority_class */
void fpcPi_Delete(process_priority_class*) {
    /* Nonmatching */
}

/* 8003FD8C-8003FDC0       .text fpcPi_IsNormal__FUiUsUs */
void fpcPi_IsNormal(unsigned int, unsigned short, unsigned short) {
    /* Nonmatching */
}

/* 8003FDC0-8003FF00       .text fpcPi_Change__FP22process_priority_classUiUsUs */
void fpcPi_Change(process_priority_class*, unsigned int, unsigned short, unsigned short) {
    /* Nonmatching */
}

/* 8003FF00-8003FF94       .text fpcPi_Handler__Fv */
void fpcPi_Handler() {
    /* Nonmatching */
}

/* 8003FF94-8004003C       .text fpcPi_Init__FP22process_priority_classPvUiUsUs */
void fpcPi_Init(process_priority_class*, void*, unsigned int, unsigned short, unsigned short) {
    /* Nonmatching */
}
