//
// Generated by dtk
// Translation Unit: f_pc_create_iter.cpp
//

#include "f_pc/f_pc_create_iter.h"
#include "dolphin/types.h"

/* 8003CC08-8003CC44       .text fpcCtIt_Method__FPFPvPv_iPv */
void fpcCtIt_Method(int (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003CC44-8003CC80       .text fpcCtIt_Judge__FPFPvPv_PvPv */
void fpcCtIt_Judge(void* (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003CC80-8003CCD4       .text fpcCtIt_filter_JudgeInLayer__FP10create_tagP16fpcCtIt_jilprm_c */
void fpcCtIt_filter_JudgeInLayer(create_tag*, fpcCtIt_jilprm_c*) {
    /* Nonmatching */
}

/* 8003CCD4-8003CD0C       .text fpcCtIt_JudgeInLayer__FUiPFPvPv_PvPv */
void fpcCtIt_JudgeInLayer(unsigned int, void* (*)(void*, void*), void*) {
    /* Nonmatching */
}
