//
// Generated by dtk
// Translation Unit: f_pc_line.cpp
//

#include "f_pc/f_pc_line.h"
#include "dolphin/types.h"

/* 8003E1DC-8003E230       .text fpcLn_Create__Fv */
void fpcLn_Create() {
    /* Nonmatching */
}
