//
// Generated by dtk
// Translation Unit: f_pc_deletor.cpp
//

#include "f_pc/f_pc_deletor.h"
#include "dolphin/types.h"

/* 8003D280-8003D2A0       .text fpcDt_IsComplete__Fv */
void fpcDt_IsComplete() {
    /* Nonmatching */
}

/* 8003D2A0-8003D314       .text fpcDt_deleteMethod__FP18base_process_class */
void fpcDt_deleteMethod(base_process_class*) {
    /* Nonmatching */
}

/* 8003D314-8003D34C       .text fpcDt_Handler__Fv */
void fpcDt_Handler() {
    /* Nonmatching */
}

/* 8003D34C-8003D3C8       .text fpcDt_ToQueue__FP18base_process_class */
void fpcDt_ToQueue(base_process_class*) {
    /* Nonmatching */
}

/* 8003D3C8-8003D51C       .text fpcDt_ToDeleteQ__FP18base_process_class */
void fpcDt_ToDeleteQ(base_process_class*) {
    /* Nonmatching */
}

/* 8003D51C-8003D580       .text fpcDt_Delete__FPv */
void fpcDt_Delete(void*) {
    /* Nonmatching */
}
