//
// Generated by dtk
// Translation Unit: f_pc_executor.cpp
//

#include "f_pc/f_pc_executor.h"
#include "dolphin/types.h"

/* 8003D5B0-8003D5D0       .text fpcEx_Search__FPFPvPv_PvPv */
void fpcEx_Search(void* (*)(void*, void*), void*) {
    /* Nonmatching */
}

/* 8003D5D0-8003D614       .text fpcEx_SearchByID__FUi */
void fpcEx_SearchByID(unsigned int) {
    /* Nonmatching */
}

/* 8003D614-8003D63C       .text fpcEx_IsExist__FUi */
void fpcEx_IsExist(unsigned int) {
    /* Nonmatching */
}

/* 8003D63C-8003D690       .text fpcEx_Execute__FP18base_process_class */
void fpcEx_Execute(base_process_class*) {
    /* Nonmatching */
}

/* 8003D690-8003D73C       .text fpcEx_ToLineQ__FP18base_process_class */
void fpcEx_ToLineQ(base_process_class*) {
    /* Nonmatching */
}

/* 8003D73C-8003D788       .text fpcEx_ExecuteQTo__FP18base_process_class */
void fpcEx_ExecuteQTo(base_process_class*) {
    /* Nonmatching */
}

/* 8003D788-8003D7E0       .text fpcEx_ToExecuteQ__FP18base_process_class */
void fpcEx_ToExecuteQ(base_process_class*) {
    /* Nonmatching */
}

/* 8003D7E0-8003D800       .text fpcEx_Handler__FPFPvPv_i */
void fpcEx_Handler(int (*)(void*, void*)) {
    /* Nonmatching */
}
