//
// Generated by dtk
// Translation Unit: f_pc_profile_lst.cpp
//

#include "f_pc/f_pc_profile_lst.h"
#include "dolphin/types.h"

/* 00000078-0000008C       .text ModuleProlog */
void ModuleProlog {
    /* Nonmatching */
}

/* 0000008C-0000009C       .text ModuleEpilog */
void ModuleEpilog {
    /* Nonmatching */
}
