//
// Generated by dtk
// Translation Unit: f_pc_method_iter.cpp
//

#include "f_pc/f_pc_method_iter.h"
#include "dolphin/types.h"

/* 8004023C-80040260       .text fpcMtdIt_Method__FP15node_list_classPFPv_i */
void fpcMtdIt_Method(node_list_class*, int (*)(void*)) {
    /* Nonmatching */
}
