//
// Generated by dtk
// Translation Unit: f_pc_layer.cpp
//

#include "f_pc/f_pc_layer.h"
#include "dolphin/types.h"

/* 8003D800-8003D820       .text fpcLy_CancelQTo__FP24process_method_tag_class */
void fpcLy_CancelQTo(process_method_tag_class*) {
    /* Nonmatching */
}

/* 8003D820-8003D844       .text fpcLy_ToCancelQ__FP11layer_classP24process_method_tag_class */
void fpcLy_ToCancelQ(layer_class*, process_method_tag_class*) {
    /* Nonmatching */
}

/* 8003D844-8003D870       .text fpcLy_CancelMethod__FP24process_method_tag_class */
void fpcLy_CancelMethod(process_method_tag_class*) {
    /* Nonmatching */
}

/* 8003D870-8003D894       .text fpcLy_IntoQueue__FP11layer_classiP16create_tag_classi */
void fpcLy_IntoQueue(layer_class*, int, create_tag_class*, int) {
    /* Nonmatching */
}

/* 8003D894-8003D8B8       .text fpcLy_ToQueue__FP11layer_classiP16create_tag_class */
void fpcLy_ToQueue(layer_class*, int, create_tag_class*) {
    /* Nonmatching */
}

/* 8003D8B8-8003D8DC       .text fpcLy_QueueTo__FP11layer_classP16create_tag_class */
void fpcLy_QueueTo(layer_class*, create_tag_class*) {
    /* Nonmatching */
}

/* 8003D8DC-8003D8F0       .text fpcLy_IsDeletingMesg__FP11layer_class */
void fpcLy_IsDeletingMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D8F0-8003D900       .text fpcLy_DeletingMesg__FP11layer_class */
void fpcLy_DeletingMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D900-8003D918       .text fpcLy_DeletedMesg__FP11layer_class */
void fpcLy_DeletedMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D918-8003D92C       .text fpcLy_IsCreatingMesg__FP11layer_class */
void fpcLy_IsCreatingMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D92C-8003D93C       .text fpcLy_CreatingMesg__FP11layer_class */
void fpcLy_CreatingMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D93C-8003D954       .text fpcLy_CreatedMesg__FP11layer_class */
void fpcLy_CreatedMesg(layer_class*) {
    /* Nonmatching */
}

/* 8003D954-8003D964       .text fpcLy_RootLayer__Fv */
void fpcLy_RootLayer() {
    /* Nonmatching */
}

/* 8003D964-8003D96C       .text fpcLy_SetCurrentLayer__FP11layer_class */
void fpcLy_SetCurrentLayer(layer_class*) {
    /* Nonmatching */
}

/* 8003D96C-8003D974       .text fpcLy_CurrentLayer__Fv */
void fpcLy_CurrentLayer() {
    /* Nonmatching */
}

/* 8003D974-8003D9C4       .text fpcLy_Search__FUi */
void fpcLy_Search(unsigned int) {
    /* Nonmatching */
}

/* 8003D9C4-8003DA34       .text fpcLy_Layer__FUi */
void fpcLy_Layer(unsigned int) {
    /* Nonmatching */
}

/* 8003DA34-8003DA60       .text fpcLy_Regist__FP11layer_class */
void fpcLy_Regist(layer_class*) {
    /* Nonmatching */
}

/* 8003DA60-8003DB14       .text fpcLy_Delete__FP11layer_class */
void fpcLy_Delete(layer_class*) {
    /* Nonmatching */
}

/* 8003DB14-8003DB40       .text fpcLy_Cancel__FP11layer_class */
void fpcLy_Cancel(layer_class*) {
    /* Nonmatching */
}

/* 8003DB40-8003DC78       .text fpcLy_Create__FP11layer_classPvP15node_list_classi */
void fpcLy_Create(layer_class*, void*, node_list_class*, int) {
    /* Nonmatching */
}
