//
// Generated by dtk
// Translation Unit: f_pc_node_req.cpp
//

#include "f_pc/f_pc_node_req.h"
#include "dolphin/types.h"

/* 8003F29C-8003F2DC       .text fpcNdRq_RequestQTo__FP19node_create_request */
void fpcNdRq_RequestQTo(node_create_request*) {
    /* Nonmatching */
}

/* 8003F2DC-8003F328       .text fpcNdRq_ToRequestQ__FP19node_create_request */
void fpcNdRq_ToRequestQ(node_create_request*) {
    /* Nonmatching */
}

/* 8003F328-8003F380       .text fpcNdRq_phase_IsCreated__FP19node_create_request */
void fpcNdRq_phase_IsCreated(node_create_request*) {
    /* Nonmatching */
}

/* 8003F380-8003F3DC       .text fpcNdRq_phase_Create__FP19node_create_request */
void fpcNdRq_phase_Create(node_create_request*) {
    /* Nonmatching */
}

/* 8003F3DC-8003F3E4       .text fpcNdRq_phase_IsDeleteTiming__FP19node_create_request */
void fpcNdRq_phase_IsDeleteTiming(node_create_request*) {
    /* Nonmatching */
}

/* 8003F3E4-8003F414       .text fpcNdRq_phase_IsDeleted__FP19node_create_request */
void fpcNdRq_phase_IsDeleted(node_create_request*) {
    /* Nonmatching */
}

/* 8003F414-8003F468       .text fpcNdRq_phase_Delete__FP19node_create_request */
void fpcNdRq_phase_Delete(node_create_request*) {
    /* Nonmatching */
}

/* 8003F468-8003F4B0       .text fpcNdRq_DoPhase__FP19node_create_request */
void fpcNdRq_DoPhase(node_create_request*) {
    /* Nonmatching */
}

/* 8003F4B0-8003F514       .text fpcNdRq_Execute__FP19node_create_request */
void fpcNdRq_Execute(node_create_request*) {
    /* Nonmatching */
}

/* 8003F514-8003F57C       .text fpcNdRq_Delete__FP19node_create_request */
void fpcNdRq_Delete(node_create_request*) {
    /* Nonmatching */
}

/* 8003F57C-8003F5D4       .text fpcNdRq_Cancel__FP19node_create_request */
void fpcNdRq_Cancel(node_create_request*) {
    /* Nonmatching */
}

/* 8003F5D4-8003F6BC       .text fpcNdRq_Handler__Fv */
void fpcNdRq_Handler() {
    /* Nonmatching */
}

/* 8003F6BC-8003F728       .text fpcNdRq_IsPossibleTarget__FP18process_node_class */
void fpcNdRq_IsPossibleTarget(process_node_class*) {
    /* Nonmatching */
}

/* 8003F728-8003F774       .text fpcNdRq_IsIng__FP18process_node_class */
void fpcNdRq_IsIng(process_node_class*) {
    /* Nonmatching */
}

/* 8003F774-8003F8EC       .text fpcNdRq_Create__FUl */
void fpcNdRq_Create(unsigned long) {
    /* Nonmatching */
}

/* 8003F8EC-8003F988       .text fpcNdRq_ChangeNode__FUlP18process_node_classsPv */
void fpcNdRq_ChangeNode(unsigned long, process_node_class*, short, void*) {
    /* Nonmatching */
}

/* 8003F988-8003FA14       .text fpcNdRq_DeleteNode__FUlP18process_node_class */
void fpcNdRq_DeleteNode(unsigned long, process_node_class*) {
    /* Nonmatching */
}

/* 8003FA14-8003FAC0       .text fpcNdRq_CreateNode__FUlsPv */
void fpcNdRq_CreateNode(unsigned long, short, void*) {
    /* Nonmatching */
}

/* 8003FAC0-8003FB70       .text fpcNdRq_Request__FUliP18process_node_classsPvP32node_create_request_method_class */
void fpcNdRq_Request(unsigned long, int, process_node_class*, short, void*, node_create_request_method_class*) {
    /* Nonmatching */
}

/* 8003FB70-8003FBE8       .text fpcNdRq_ReChangeNode__FUisPv */
void fpcNdRq_ReChangeNode(unsigned int, short, void*) {
    /* Nonmatching */
}

/* 8003FBE8-8003FC08       .text fpcNdRq_ReRequest__FUisPv */
void fpcNdRq_ReRequest(unsigned int, short, void*) {
    /* Nonmatching */
}
