//
// Generated by dtk
// Translation Unit: f_pc_profile.cpp
//

#include "f_pc/f_pc_profile.h"
#include "dolphin/types.h"

/* 8004003C-80040050       .text fpcPf_Get__Fs */
void fpcPf_Get(short) {
    /* Nonmatching */
}
