//
// Generated by dtk
// Translation Unit: f_pc_method.cpp
//

#include "f_pc/f_pc_method.h"
#include "dolphin/types.h"

/* 8003EF00-8003EF38       .text fpcMtd_Method__FPFPv_iPv */
void fpcMtd_Method(int (*)(void*), void*) {
    /* Nonmatching */
}

/* 8003EF38-8003EF5C       .text fpcMtd_Execute__FP20process_method_classPv */
void fpcMtd_Execute(process_method_class*, void*) {
    /* Nonmatching */
}

/* 8003EF5C-8003EF80       .text fpcMtd_IsDelete__FP20process_method_classPv */
void fpcMtd_IsDelete(process_method_class*, void*) {
    /* Nonmatching */
}

/* 8003EF80-8003EFA4       .text fpcMtd_Delete__FP20process_method_classPv */
void fpcMtd_Delete(process_method_class*, void*) {
    /* Nonmatching */
}

/* 8003EFA4-8003EFC8       .text fpcMtd_Create__FP20process_method_classPv */
void fpcMtd_Create(process_method_class*, void*) {
    /* Nonmatching */
}
