//
// Generated by dtk
// Translation Unit: f_pc_method_tag.cpp
//

#include "f_pc/f_pc_method_tag.h"
#include "dolphin/types.h"

/* 80040260-80040290       .text fpcMtdTg_Do__FP24process_method_tag_class */
void fpcMtdTg_Do(process_method_tag_class*) {
    /* Nonmatching */
}

/* 80040290-800402B0       .text fpcMtdTg_ToMethodQ__FP15node_list_classP24process_method_tag_class */
void fpcMtdTg_ToMethodQ(node_list_class*, process_method_tag_class*) {
    /* Nonmatching */
}

/* 800402B0-800402D0       .text fpcMtdTg_MethodQTo__FP24process_method_tag_class */
void fpcMtdTg_MethodQTo(process_method_tag_class*) {
    /* Nonmatching */
}

/* 800402D0-8004031C       .text fpcMtdTg_Init__FP24process_method_tag_classPFPv_iPv */
void fpcMtdTg_Init(process_method_tag_class*, int (*)(void*), void*) {
    /* Nonmatching */
}
