//
// Generated by dtk
// Translation Unit: f_pc_fstcreate_req.cpp
//

#include "f_pc/f_pc_fstcreate_req.h"
#include "dolphin/types.h"

/* 80040520-80040570       .text fpcFCtRq_Do__FP19fast_create_request */
void fpcFCtRq_Do(fast_create_request*) {
    /* Nonmatching */
}

/* 80040570-80040578       .text fpcFCtRq_Delete__FP19fast_create_request */
void fpcFCtRq_Delete(fast_create_request*) {
    /* Nonmatching */
}

/* 80040578-80040648       .text fpcFCtRq_Request__FP11layer_classsPFPvPv_iPvPv */
void fpcFCtRq_Request(layer_class*, short, int (*)(void*, void*), void*, void*) {
    /* Nonmatching */
}
