//
// Generated by dtk
// Translation Unit: f_pc_layer_tag.cpp
//

#include "f_pc/f_pc_layer_tag.h"
#include "dolphin/types.h"

/* 8003DF4C-8003E044       .text fpcLyTg_ToQueue__FP26layer_management_tag_classUiUsUs */
void fpcLyTg_ToQueue(layer_management_tag_class*, unsigned int, unsigned short, unsigned short) {
    /* Nonmatching */
}

/* 8003E044-8003E0A4       .text fpcLyTg_QueueTo__FP26layer_management_tag_class */
void fpcLyTg_QueueTo(layer_management_tag_class*) {
    /* Nonmatching */
}

/* 8003E0A4-8003E128       .text fpcLyTg_Move__FP26layer_management_tag_classUiUsUs */
void fpcLyTg_Move(layer_management_tag_class*, unsigned int, unsigned short, unsigned short) {
    /* Nonmatching */
}

/* 8003E128-8003E1DC       .text fpcLyTg_Init__FP26layer_management_tag_classUiPv */
void fpcLyTg_Init(layer_management_tag_class*, unsigned int, void*) {
    /* Nonmatching */
}
