//
// Generated by dtk
// Translation Unit: f_pc_base.cpp
//

#include "f_pc/f_pc_base.h"
#include "dolphin/types.h"

/* 8003C88C-8003C89C       .text fpcBs_Is_JustOfType__Fii */
void fpcBs_Is_JustOfType(int, int) {
    /* Nonmatching */
}

/* 8003C89C-8003C8DC       .text fpcBs_MakeOfType__FPi */
void fpcBs_MakeOfType(int*) {
    /* Nonmatching */
}

/* 8003C8DC-8003C904       .text fpcBs_MakeOfId__Fv */
void fpcBs_MakeOfId() {
    /* Nonmatching */
}

/* 8003C904-8003C960       .text fpcBs_Execute__FP18base_process_class */
void fpcBs_Execute(base_process_class*) {
    /* Nonmatching */
}

/* 8003C960-8003C9A0       .text fpcBs_DeleteAppend__FP18base_process_class */
void fpcBs_DeleteAppend(base_process_class*) {
    /* Nonmatching */
}

/* 8003C9A0-8003C9FC       .text fpcBs_IsDelete__FP18base_process_class */
void fpcBs_IsDelete(base_process_class*) {
    /* Nonmatching */
}

/* 8003C9FC-8003CA60       .text fpcBs_Delete__FP18base_process_class */
void fpcBs_Delete(base_process_class*) {
    /* Nonmatching */
}

/* 8003CA60-8003CB5C       .text fpcBs_Create__FsUiPv */
void fpcBs_Create(short, unsigned int, void*) {
    /* Nonmatching */
}

/* 8003CB5C-8003CC08       .text fpcBs_SubCreate__FP18base_process_class */
void fpcBs_SubCreate(base_process_class*) {
    /* Nonmatching */
}
