//
// Generated by dtk
// Translation Unit: JKRFile.cpp
//

#include "JSystem/JKernel/JKRFile.h"
#include "dolphin/types.h"

/* 802BC610-802BC6B4       .text read__7JKRFileFPvll */
void JKRFile::read(void*, long, long) {
    /* Nonmatching */
}
