//
// Generated by dtk
// Translation Unit: d_resorce.cpp
//

#include "d_resorce.h"
#include "dolphin/types.h"

/* 8006D804-8006D824       .text __ct__11dRes_info_cFv */
dRes_info_c::dRes_info_c() {
    /* Nonmatching */
}

/* 8006D824-8006D8F4       .text __dt__11dRes_info_cFv */
dRes_info_c::~dRes_info_c() {
    /* Nonmatching */
}

/* 8006D8F4-8006D990       .text set__11dRes_info_cFPCcPCcUcP7JKRHeap */
void dRes_info_c::set(const char*, const char*, unsigned char, JKRHeap*) {
    /* Nonmatching */
}

/* 8006D990-8006DCEC       .text setToonTex__FP12J3DModelData */
void setToonTex(J3DModelData*) {
    /* Nonmatching */
}

/* 8006DCEC-8006DFD4       .text setToonTex__FP16J3DMaterialTable */
void setToonTex(J3DMaterialTable*) {
    /* Nonmatching */
}

/* 8006DFD4-8006E7A4       .text loadResource__11dRes_info_cFv */
void dRes_info_c::loadResource() {
    /* Nonmatching */
}

/* 8006E7A4-8006E7EC       .text __dt__13JKRFileFinderFv */
JKRFileFinder::~JKRFileFinder() {
    /* Nonmatching */
}

/* 8006E7EC-8006E858       .text __dt__18J3DAnmTransformKeyFv */
J3DAnmTransformKey::~J3DAnmTransformKey() {
    /* Nonmatching */
}

/* 8006E858-8006E8B4       .text __dt__15J3DAnmTransformFv */
J3DAnmTransform::~J3DAnmTransform() {
    /* Nonmatching */
}

/* 8006E8B4-8006E8FC       .text __dt__10J3DAnmBaseFv */
J3DAnmBase::~J3DAnmBase() {
    /* Nonmatching */
}

/* 8006E8FC-8006EBD0       .text setRes__11dRes_info_cFv */
void dRes_info_c::setRes() {
    /* Nonmatching */
}

/* 8006EBD0-8006EBF8       .text getArcHeader__FP10JKRArchive */
void getArcHeader(JKRArchive*) {
    /* Nonmatching */
}

/* 8006EBF8-8006ECF4       .text dump_long__11dRes_info_cFP11dRes_info_ci */
void dRes_info_c::dump_long(dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006ECF4-8006EE6C       .text dump__11dRes_info_cFP11dRes_info_ci */
void dRes_info_c::dump(dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006EE6C-8006EF34       .text __dt__14dRes_control_cFv */
dRes_control_c::~dRes_control_c() {
    /* Nonmatching */
}

/* 8006EF34-8006F01C       .text setRes__14dRes_control_cFPCcP11dRes_info_ciPCcUcP7JKRHeap */
void dRes_control_c::setRes(const char*, dRes_info_c*, int, const char*, unsigned char, JKRHeap*) {
    /* Nonmatching */
}

/* 8006F01C-8006F074       .text syncRes__14dRes_control_cFPCcP11dRes_info_ci */
void dRes_control_c::syncRes(const char*, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F074-8006F0E8       .text deleteRes__14dRes_control_cFPCcP11dRes_info_ci */
void dRes_control_c::deleteRes(const char*, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F0E8-8006F164       .text getResInfo__14dRes_control_cFPCcP11dRes_info_ci */
void dRes_control_c::getResInfo(const char*, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F164-8006F18C       .text newResInfo__14dRes_control_cFP11dRes_info_ci */
void dRes_control_c::newResInfo(dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F18C-8006F208       .text getResInfoLoaded__14dRes_control_cFPCcP11dRes_info_ci */
void dRes_control_c::getResInfoLoaded(const char*, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F208-8006F298       .text getRes__14dRes_control_cFPCclP11dRes_info_ci */
void dRes_control_c::getRes(const char*, long, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F298-8006F34C       .text getRes__14dRes_control_cFPCcPCcP11dRes_info_ci */
void dRes_control_c::getRes(const char*, const char*, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F34C-8006F3BC       .text getIDRes__14dRes_control_cFPCcUsP11dRes_info_ci */
void dRes_control_c::getIDRes(const char*, unsigned short, dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F3BC-8006F430       .text syncAllRes__14dRes_control_cFP11dRes_info_ci */
void dRes_control_c::syncAllRes(dRes_info_c*, int) {
    /* Nonmatching */
}

/* 8006F430-8006F500       .text setStageRes__14dRes_control_cFPCcP7JKRHeap */
void dRes_control_c::setStageRes(const char*, JKRHeap*) {
    /* Nonmatching */
}

/* 8006F500-8006F580       .text dump__14dRes_control_cFv */
void dRes_control_c::dump() {
    /* Nonmatching */
}

/* 8006F580-8006F5FC       .text __dt__18mDoExt_transAnmBasFv */
mDoExt_transAnmBas::~mDoExt_transAnmBas() {
    /* Nonmatching */
}

/* 8006F5FC-8006F62C       .text getTransform__18J3DAnmTransformKeyCFUsP16J3DTransformInfo */
void J3DAnmTransformKey::getTransform(unsigned short, J3DTransformInfo*) const {
    /* Nonmatching */
}

