//
// Generated by dtk
// Translation Unit: JPATexture.cpp
//

#include "JSystem/JPALoader/JPATexture.h"
#include "dolphin/types.h"

/* 80258660-802586D0       .text __ct__13JPATextureArcFPCUc */
JPATextureArc::JPATextureArc(const unsigned char*) {
    /* Nonmatching */
}

/* 802586D0-80258BB4       .text initialize__17JPADefaultTextureFP7JKRHeap */
void JPADefaultTexture::initialize(JKRHeap*) {
    /* Nonmatching */
}

/* 80258BB4-80258BFC       .text __dt__10JPATextureFv */
JPATexture::~JPATexture() {
    /* Nonmatching */
}

/* 80258BFC-80258C74       .text __dt__13JPATextureArcFv */
JPATextureArc::~JPATextureArc() {
    /* Nonmatching */
}

/* 80258C74-80258C80       .text getName__13JPATextureArcCFv */
void JPATextureArc::getName() const {
    /* Nonmatching */
}

/* 80258C80-80258CA4       .text load__13JPATextureArcF11_GXTexMapID */
void JPATextureArc::load(_GXTexMapID) {
    /* Nonmatching */
}

/* 80258CA4-80258CAC       .text getJUTTexture__13JPATextureArcFv */
void JPATextureArc::getJUTTexture() {
    /* Nonmatching */
}
