//
// Generated by dtk
// Translation Unit: d_com_lib_game.cpp
//

#include "d_com_lib_game.h"
#include "dolphin/types.h"

/* 800565CC-8005662C       .text dComLbG_PhaseHandler__FP30request_of_phase_process_classPPFPv_iPv */
void dComLbG_PhaseHandler(request_of_phase_process_class*, int (**)(void*), void*) {
    /* Nonmatching */
}

