//
// Generated by dtk
// Translation Unit: JSUFileStream.cpp
//

#include "JSystem/JSupport/JSUFileStream.h"
#include "dolphin/types.h"

/* 802BF81C-802BF860       .text __ct__18JSUFileInputStreamFP7JKRFile */
JSUFileInputStream::JSUFileInputStream(JKRFile*) {
    /* Nonmatching */
}

/* 802BF860-802BF930       .text readData__18JSUFileInputStreamFPvl */
void JSUFileInputStream::readData(void*, long) {
    /* Nonmatching */
}

/* 802BF930-802BFA10       .text seekPos__18JSUFileInputStreamFl17JSUStreamSeekFrom */
void JSUFileInputStream::seekPos(long, JSUStreamSeekFrom) {
    /* Nonmatching */
}

/* 802BFA10-802BFA40       .text getLength__18JSUFileInputStreamCFv */
void JSUFileInputStream::getLength() const {
    /* Nonmatching */
}

/* 802BFA40-802BFA48       .text getPosition__18JSUFileInputStreamCFv */
void JSUFileInputStream::getPosition() const {
    /* Nonmatching */
}
