//
// Generated by dtk
// Translation Unit: JSUInputStream.cpp
//

#include "JSystem/JSupport/JSUInputStream.h"
#include "dolphin/types.h"

/* 802BF3F4-802BF47C       .text __dt__14JSUInputStreamFv */
JSUInputStream::~JSUInputStream() {
    /* Nonmatching */
}

/* 802BF47C-802BF4D4       .text read__14JSUInputStreamFPvl */
void JSUInputStream::read(void*, long) {
    /* Nonmatching */
}

/* 802BF4D4-802BF554       .text skip__14JSUInputStreamFl */
void JSUInputStream::skip(long) {
    /* Nonmatching */
}

/* 802BF554-802BF5E0       .text align__20JSURandomInputStreamFl */
void JSURandomInputStream::align(long) {
    /* Nonmatching */
}

/* 802BF5E0-802BF63C       .text skip__20JSURandomInputStreamFl */
void JSURandomInputStream::skip(long) {
    /* Nonmatching */
}

/* 802BF63C-802BF6C0       .text peek__20JSURandomInputStreamFPvl */
void JSURandomInputStream::peek(void*, long) {
    /* Nonmatching */
}

/* 802BF6C0-802BF704       .text seek__20JSURandomInputStreamFl17JSUStreamSeekFrom */
void JSURandomInputStream::seek(long, JSUStreamSeekFrom) {
    /* Nonmatching */
}
