//
// Generated by dtk
// Translation Unit: JSUList.cpp
//

#include "JSystem/JSupport/JSUList.h"
#include "dolphin/types.h"

/* 802BEFE4-802BEFFC       .text __ct__10JSUPtrLinkFPv */
JSUPtrLink::JSUPtrLink(void*) {
    /* Nonmatching */
}

/* 802BEFFC-802BF05C       .text __dt__10JSUPtrLinkFv */
JSUPtrLink::~JSUPtrLink() {
    /* Nonmatching */
}

/* 802BF05C-802BF094       .text __ct__10JSUPtrListFb */
JSUPtrList::JSUPtrList(bool) {
    /* Nonmatching */
}

/* 802BF094-802BF0FC       .text __dt__10JSUPtrListFv */
JSUPtrList::~JSUPtrList() {
    /* Nonmatching */
}

/* 802BF0FC-802BF110       .text initiate__10JSUPtrListFv */
void JSUPtrList::initiate() {
    /* Nonmatching */
}

/* 802BF110-802BF134       .text setFirst__10JSUPtrListFP10JSUPtrLink */
void JSUPtrList::setFirst(JSUPtrLink*) {
    /* Nonmatching */
}

/* 802BF134-802BF1D8       .text append__10JSUPtrListFP10JSUPtrLink */
void JSUPtrList::append(JSUPtrLink*) {
    /* Nonmatching */
}

/* 802BF1D8-802BF27C       .text prepend__10JSUPtrListFP10JSUPtrLink */
void JSUPtrList::prepend(JSUPtrLink*) {
    /* Nonmatching */
}

/* 802BF27C-802BF344       .text insert__10JSUPtrListFP10JSUPtrLinkP10JSUPtrLink */
void JSUPtrList::insert(JSUPtrLink*, JSUPtrLink*) {
    /* Nonmatching */
}

/* 802BF344-802BF3F4       .text remove__10JSUPtrListFP10JSUPtrLink */
void JSUPtrList::remove(JSUPtrLink*) {
    /* Nonmatching */
}
