//
// Generated by dtk
// Translation Unit: JSUMemoryStream.cpp
//

#include "JSystem/JSupport/JSUMemoryStream.h"
#include "dolphin/types.h"

/* 802BF704-802BF718       .text setBuffer__20JSUMemoryInputStreamFPCvl */
void JSUMemoryInputStream::setBuffer(const void*, long) {
    /* Nonmatching */
}

/* 802BF718-802BF790       .text readData__20JSUMemoryInputStreamFPvl */
void JSUMemoryInputStream::readData(void*, long) {
    /* Nonmatching */
}

/* 802BF790-802BF80C       .text seekPos__20JSUMemoryInputStreamFl17JSUStreamSeekFrom */
void JSUMemoryInputStream::seekPos(long, JSUStreamSeekFrom) {
    /* Nonmatching */
}

/* 802BF80C-802BF814       .text getLength__20JSUMemoryInputStreamCFv */
void JSUMemoryInputStream::getLength() const {
    /* Nonmatching */
}

/* 802BF814-802BF81C       .text getPosition__20JSUMemoryInputStreamCFv */
void JSUMemoryInputStream::getPosition() const {
    /* Nonmatching */
}
