//
// Generated by dtk
// Translation Unit: DynamicLink.o
//

#include "DynamicLink.h"
#include "dolphin/types.h"

/* 80240098-80240150       .text __dt__24DynamicModuleControlBaseFv */
DynamicModuleControlBase::~DynamicModuleControlBase() {
    /* Nonmatching */
}

/* 80240150-8024019C       .text __ct__24DynamicModuleControlBaseFv */
DynamicModuleControlBase::DynamicModuleControlBase() {
    /* Nonmatching */
}

/* 8024019C-802402A0       .text link__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::link() {
    /* Nonmatching */
}

/* 802402A0-8024035C       .text unlink__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::unlink() {
    /* Nonmatching */
}

/* 8024035C-8024039C       .text load_async__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::load_async() {
    /* Nonmatching */
}

/* 8024039C-802403E0       .text force_unlink__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::force_unlink() {
    /* Nonmatching */
}

/* 802403E0-802405BC       .text dump__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::dump() {
    /* Nonmatching */
}

/* 802405BC-8024062C       .text __ct__20DynamicModuleControlFPCc */
DynamicModuleControl::DynamicModuleControl(const char*) {
    /* Nonmatching */
}

/* 8024062C-802406B8       .text mountCallback__20DynamicModuleControlFPv */
void DynamicModuleControl::mountCallback(void*) {
    /* Nonmatching */
}

/* 802406B8-802406F0       .text initialize__20DynamicModuleControlFv */
void DynamicModuleControl::initialize() {
    /* Nonmatching */
}

/* 802406F0-8024071C       .text callback__20DynamicModuleControlFPv */
void DynamicModuleControl::callback(void*) {
    /* Nonmatching */
}

/* 8024071C-80240744       .text calcSum2__FPCUsUl */
void calcSum2(const unsigned short*, unsigned long) {
    /* Nonmatching */
}

/* 80240744-80240A48       .text do_load__20DynamicModuleControlFv */
void DynamicModuleControl::do_load() {
    /* Nonmatching */
}

/* 80240A48-80240B10       .text do_load_async__20DynamicModuleControlFv */
void DynamicModuleControl::do_load_async() {
    /* Nonmatching */
}

/* 80240B10-80240B58       .text do_unload__20DynamicModuleControlFv */
void DynamicModuleControl::do_unload() {
    /* Nonmatching */
}

/* 80240B58-80240BB4       .text dump2__20DynamicModuleControlFv */
void DynamicModuleControl::dump2() {
    /* Nonmatching */
}

/* 80240BB4-80240F54       .text do_link__20DynamicModuleControlFv */
void DynamicModuleControl::do_link() {
    /* Nonmatching */
}

/* 80240F54-8024102C       .text do_unlink__20DynamicModuleControlFv */
void DynamicModuleControl::do_unlink() {
    /* Nonmatching */
}

/* 8024102C-8024109C       .text getModuleSize__20DynamicModuleControlCFv */
void DynamicModuleControl::getModuleSize() const {
    /* Nonmatching */
}

/* 8024109C-802410B4       .text getModuleTypeString__20DynamicModuleControlCFv */
void DynamicModuleControl::getModuleTypeString() const {
    /* Nonmatching */
}

/* 802410B4-802410B8       .text ModuleProlog */
extern "C" void ModuleProlog() {
    /* empty */
}

/* 802410B8-802410BC       .text ModuleEpilog */
extern "C" void ModuleEpilog() {
    /* empty */
}

/* 802410BC-80241178       .text ModuleUnresolved */
extern "C" void ModuleUnresolved() {
    /* Nonmatching */
}

/* 80241178-802411F8       .text ModuleConstructorsX */
extern "C" void ModuleConstructorsX() {
    /* Nonmatching */
}

/* 802411F8-80241278       .text ModuleDestructorsX */
extern "C" void ModuleDestructorsX() {
    /* Nonmatching */
}

/* 80241278-80241280       .text do_link__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::do_link() {
    /* Nonmatching */
}

/* 80241280-80241288       .text do_load__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::do_load() {
    /* Nonmatching */
}

/* 80241288-80241290       .text do_unload__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::do_unload() {
    /* Nonmatching */
}

/* 80241290-80241298       .text do_unlink__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::do_unlink() {
    /* Nonmatching */
}

/* 80241298-802412A0       .text do_load_async__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::do_load_async() {
    /* Nonmatching */
}

/* 802412A0-802412A4       .text dump2__24DynamicModuleControlBaseFv */
void DynamicModuleControlBase::dump2() {
    /* Nonmatching */
}

/* 802412A4-802412B4       .text getModuleTypeString__24DynamicModuleControlBaseCFv */
void DynamicModuleControlBase::getModuleTypeString() const {
    /* Nonmatching */
}

/* 802412B4-802412BC       .text getModuleSize__24DynamicModuleControlBaseCFv */
void DynamicModuleControlBase::getModuleSize() const {
    /* Nonmatching */
}

/* 802412BC-802412C4       .text getModuleName__20DynamicModuleControlCFv */
void DynamicModuleControl::getModuleName() const {
    /* Nonmatching */
}

/* 802412C4-802412F0       .text getExpandedResSize__10JKRArchiveCFPCv */
void JKRArchive::getExpandedResSize(const void*) const {
    /* Nonmatching */
}
