//
// Generated by dtk
// Translation Unit: f_op_kankyo_mng.cpp
//

#include "f_op/f_op_kankyo_mng.h"
#include "dolphin/types.h"

/* 8002A860-8002A880       .text fopKyM_SearchByID__FUi */
void fopKyM_SearchByID(unsigned int) {
    /* Nonmatching */
}

/* 8002A880-8002A8D8       .text fopKyM_CreateAppend__Fv */
void fopKyM_CreateAppend() {
    /* Nonmatching */
}

/* 8002A8D8-8002A968       .text createAppend__FiP4cXyzP4cXyz */
void createAppend(int, cXyz*, cXyz*) {
    /* Nonmatching */
}

/* 8002A968-8002A988       .text fopKyM_Delete__FPv */
void fopKyM_Delete(void*) {
    /* Nonmatching */
}

/* 8002A988-8002A9D8       .text fopKyM_Create__FsPFPv_iPv */
void fopKyM_Create(short, int (*)(void*), void*) {
    /* Nonmatching */
}

/* 8002A9D8-8002AA38       .text fopKyM_create__FsiP4cXyzP4cXyzPFPv_i */
void fopKyM_create(short, int, cXyz*, cXyz*, int (*)(void*)) {
    /* Nonmatching */
}

/* 8002AA38-8002AA9C       .text fopKyM_fastCreate__FsiP4cXyzP4cXyzPFPv_i */
void fopKyM_fastCreate(short, int, cXyz*, cXyz*, int (*)(void*)) {
    /* Nonmatching */
}

/* 8002AA9C-8002AB40       .text fopKyM_createWpillar__FPC4cXyzffi */
void fopKyM_createWpillar(const cXyz*, float, float, int) {
    /* Nonmatching */
}

/* 8002AB40-8002ABB4       .text fopKyM_createMpillar__FPC4cXyzf */
void fopKyM_createMpillar(const cXyz*, float) {
    /* Nonmatching */
}
