//
// Generated by dtk
// Translation Unit: f_op_camera_mng.cpp
//

#include "f_op/f_op_camera_mng.h"
#include "dolphin/types.h"

/* 80029468-80029470       .text fopCamM_GetParam__FP12camera_class */
void fopCamM_GetParam(camera_class*) {
    /* Nonmatching */
}

/* 80029470-800294D4       .text fopCamM_Create__FisPv */
void fopCamM_Create(int, short, void*) {
    /* Nonmatching */
}

/* 800294D4-800294D8       .text fopCamM_Management__Fv */
void fopCamM_Management() {
    /* Nonmatching */
}

/* 800294D8-800294DC       .text fopCamM_Init__Fv */
void fopCamM_Init() {
    /* Nonmatching */
}
