//
// Generated by dtk
// Translation Unit: f_op_draw_iter.cpp
//

#include "f_op/f_op_draw_iter.h"
#include "dolphin/types.h"

/* 8003C640-8003C684       .text fopDwIt_GetTag__Fv */
void fopDwIt_GetTag() {
    /* Nonmatching */
}

/* 8003C684-8003C6C0       .text fopDwIt_Begin__Fv */
void fopDwIt_Begin() {
    /* Nonmatching */
}

/* 8003C6C0-8003C6EC       .text fopDwIt_Next__FP16create_tag_class */
void fopDwIt_Next(create_tag_class*) {
    /* Nonmatching */
}
