//
// Generated by dtk
// Translation Unit: f_op_msg.cpp
//

#include "f_op/f_op_msg.h"
#include "dolphin/types.h"

/* 8002A688-8002A6B0       .text fopMsg_Draw__FPv */
void fopMsg_Draw(void*) {
    /* Nonmatching */
}

/* 8002A6B0-8002A6E8       .text fopMsg_Execute__FPv */
void fopMsg_Execute(void*) {
    /* Nonmatching */
}

/* 8002A6E8-8002A73C       .text fopMsg_IsDelete__FPv */
void fopMsg_IsDelete(void*) {
    /* Nonmatching */
}

/* 8002A73C-8002A788       .text fopMsg_Delete__FPv */
void fopMsg_Delete(void*) {
    /* Nonmatching */
}

/* 8002A788-8002A860       .text fopMsg_Create__FPv */
void fopMsg_Create(void*) {
    /* Nonmatching */
}
