//
// Generated by dtk
// Translation Unit: d_s_title.cpp
//

#include "d_s_title.h"
#include "dolphin/types.h"

/* 802372F4-80237344       .text dScnTitle_Draw__FP20title_of_scene_class */
void dScnTitle_Draw(title_of_scene_class*) {
    /* Nonmatching */
}

/* 80237344-802374C8       .text dScnTitle_Execute__FP20title_of_scene_class */
void dScnTitle_Execute(title_of_scene_class*) {
    /* Nonmatching */
}

/* 802374C8-802374D0       .text dScnTitle_IsDelete__FP20title_of_scene_class */
void dScnTitle_IsDelete(title_of_scene_class*) {
    /* Nonmatching */
}

/* 802374D0-802374D8       .text dScnTitle_Delete__FP20title_of_scene_class */
void dScnTitle_Delete(title_of_scene_class*) {
    /* Nonmatching */
}

/* 802374D8-80237568       .text dScnTitle_Create__FP11scene_class */
void dScnTitle_Create(scene_class*) {
    /* Nonmatching */
}

